//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurtleMine.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TurtleMine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Word (Empty for a blank entry): ähnelt.
        /// </summary>
        internal static string AddWord {
            get {
                return ResourceManager.GetString("AddWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Word ähnelt.
        /// </summary>
        internal static string AddWord_Title {
            get {
                return ResourceManager.GetString("AddWord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status : Download complete. {0} Issues displayed. ähnelt.
        /// </summary>
        internal static string AtomLoadComplete {
            get {
                return ResourceManager.GetString("AtomLoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status : Download failed ähnelt.
        /// </summary>
        internal static string AtomLoadFailed {
            get {
                return ResourceManager.GetString("AtomLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status : Loading ATOM feed ähnelt.
        /// </summary>
        internal static string AtomLoading {
            get {
                return ResourceManager.GetString("AtomLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OpenProject ähnelt.
        /// </summary>
        internal static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author ähnelt.
        /// </summary>
        internal static string ColumnAuthor {
            get {
                return ResourceManager.GetString("ColumnAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Updated ähnelt.
        /// </summary>
        internal static string ColumnLastUpdated {
            get {
                return ResourceManager.GetString("ColumnLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # ähnelt.
        /// </summary>
        internal static string ColumnNumber {
            get {
                return ResourceManager.GetString("ColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        internal static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary ähnelt.
        /// </summary>
        internal static string ColumnSummary {
            get {
                return ResourceManager.GetString("ColumnSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        internal static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TurtleMine Configuration ähnelt.
        /// </summary>
        internal static string Configuration_loadControls_Configuration_Utility {
            get {
                return ResourceManager.GetString("Configuration_loadControls_Configuration_Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TurtleMine Configuration - Project Settings ähnelt.
        /// </summary>
        internal static string Configuration_LoadControlsProject_Configuration_Utility___Project_Settings {
            get {
                return ResourceManager.GetString("Configuration_LoadControlsProject_Configuration_Utility___Project_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you wish to delete this item? ähnelt.
        /// </summary>
        internal static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Delete ähnelt.
        /// </summary>
        internal static string Confirm_Delete_Title {
            get {
                return ResourceManager.GetString("Confirm_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you wish to reset to default? All Changes will be lost! ähnelt.
        /// </summary>
        internal static string Confirm_Reset {
            get {
                return ResourceManager.GetString("Confirm_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Reset ähnelt.
        /// </summary>
        internal static string Confirm_Reset_Title {
            get {
                return ResourceManager.GetString("Confirm_Reset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Files ähnelt.
        /// </summary>
        internal static string Connectivity_btnSSLPath_Click_All_Files {
            get {
                return ResourceManager.GetString("Connectivity_btnSSLPath_Click_All_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certificate Files ähnelt.
        /// </summary>
        internal static string Connectivity_btnSSLPath_Click_Certificate_Files {
            get {
                return ResourceManager.GetString("Connectivity_btnSSLPath_Click_Certificate_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Certificate File ähnelt.
        /// </summary>
        internal static string Connectivity_btnSSLPath_Click_Select_Certificate_File {
            get {
                return ResourceManager.GetString("Connectivity_btnSSLPath_Click_Select_Certificate_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must keep at least one column! ähnelt.
        /// </summary>
        internal static string ErrorColumnRequiredMessage {
            get {
                return ResourceManager.GetString("ErrorColumnRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column Missing ähnelt.
        /// </summary>
        internal static string ErrorColumnRequiredTitle {
            get {
                return ResourceManager.GetString("ErrorColumnRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you wish to continue anyway? ähnelt.
        /// </summary>
        internal static string ErrorConfirmContinue {
            get {
                return ResourceManager.GetString("ErrorConfirmContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem establishing a connection to check for updates:{0} ähnelt.
        /// </summary>
        internal static string ErrorInUpdatesConnectionMessage {
            get {
                return ResourceManager.GetString("ErrorInUpdatesConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to check for updates ähnelt.
        /// </summary>
        internal static string ErrorInUpdatesConnectionTitle {
            get {
                return ResourceManager.GetString("ErrorInUpdatesConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error has occurred retrieving the issue list:{0} ähnelt.
        /// </summary>
        internal static string ErrorReadingIssuesListMessage {
            get {
                return ResourceManager.GetString("ErrorReadingIssuesListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to read issue list ähnelt.
        /// </summary>
        internal static string ErrorReadingIssuesListTitle {
            get {
                return ResourceManager.GetString("ErrorReadingIssuesListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must keep at least one word in the list! ähnelt.
        /// </summary>
        internal static string ErrorWordRequiredMessage {
            get {
                return ResourceManager.GetString("ErrorWordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Word Missing ähnelt.
        /// </summary>
        internal static string ErrorWordRequiredTitle {
            get {
                return ResourceManager.GetString("ErrorWordRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die feedUrl is not provided. Please confirm the plugin settings in Tortoise. ähnelt.
        /// </summary>
        internal static string FeedParser_feedUrl_is_not_provided {
            get {
                return ResourceManager.GetString("FeedParser_feedUrl_is_not_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Hide ähnelt.
        /// </summary>
        internal static string HidePassword {
            get {
                return ResourceManager.GetString("HidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import / Export ähnelt.
        /// </summary>
        internal static string ImportExport {
            get {
                return ResourceManager.GetString("ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Issue ähnelt.
        /// </summary>
        internal static string IssueText {
            get {
                return ResourceManager.GetString("IssueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success ähnelt.
        /// </summary>
        internal static string OptionsDialog_btnTest_Click_Success {
            get {
                return ResourceManager.GetString("OptionsDialog_btnTest_Click_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully read atom feed: {0} ähnelt.
        /// </summary>
        internal static string OptionsDialog_btnTest_Click_Successfully_read_atom_feed {
            get {
                return ResourceManager.GetString("OptionsDialog_btnTest_Click_Successfully_read_atom_feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed ähnelt.
        /// </summary>
        internal static string OptionsDialog_lnkFeedUrl_LinkClicked_Failed {
            get {
                return ResourceManager.GetString("OptionsDialog_lnkFeedUrl_LinkClicked_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to open link! ähnelt.
        /// </summary>
        internal static string OptionsDialog_lnkFeedUrl_LinkClicked_Unable_to_open_link {
            get {
                return ResourceManager.GetString("OptionsDialog_lnkFeedUrl_LinkClicked_Unable_to_open_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Repository Location ähnelt.
        /// </summary>
        internal static string ProjectDetails_btnRepoPath_Click_Select_Repository_Location {
            get {
                return ResourceManager.GetString("ProjectDetails_btnRepoPath_Click_Select_Repository_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This directory can not be identified as a know repository folder for Subversion, Git or Mecurial. ähnelt.
        /// </summary>
        internal static string ProjectDetails_btnRepoPath_Click_This_directory_can_not_be_identified_1 {
            get {
                return ResourceManager.GetString("ProjectDetails_btnRepoPath_Click_This_directory_can_not_be_identified_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you wish to continue anyway? ähnelt.
        /// </summary>
        internal static string ProjectDetails_btnRepoPath_Click_This_directory_can_not_be_identified_2 {
            get {
                return ResourceManager.GetString("ProjectDetails_btnRepoPath_Click_This_directory_can_not_be_identified_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Repository Type ähnelt.
        /// </summary>
        internal static string ProjectDetails_btnRepoPath_Click_Unknown_Repository_Type {
            get {
                return ResourceManager.GetString("ProjectDetails_btnRepoPath_Click_Unknown_Repository_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redmine &amp;Issues ähnelt.
        /// </summary>
        internal static string Redmine {
            get {
                return ResourceManager.GetString("Redmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refs ähnelt.
        /// </summary>
        internal static string RefsText {
            get {
                return ResourceManager.GetString("RefsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        internal static string SearchBoxNoResults {
            get {
                return ResourceManager.GetString("SearchBoxNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search : {0} occurrence(s) ähnelt.
        /// </summary>
        internal static string SearchBoxWithResults {
            get {
                return ResourceManager.GetString("SearchBoxWithResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Fields ähnelt.
        /// </summary>
        internal static string SearchFieldAllFields {
            get {
                return ResourceManager.GetString("SearchFieldAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S&amp;how ähnelt.
        /// </summary>
        internal static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
    }
}
